
% 20 Eastbound and Westbound trains

train(east,[c(1,rectangle,short,not_double,none,2,l(circle,1)),c(2,rectangle,
	long,not_double,none,3,l(hexagon,1)),c(3,rectangle,short,
	not_double,peaked,2,l(triangle,1)),c(4,rectangle,long,
	not_double,none,2,l(rectangle,3))]).
train(east,[c(1,rectangle,short,not_double,flat,2,l(circle,2)),c(2,bucket,
	short,not_double,none,2,l(rectangle,1)),c(3,u_shaped,
	short,not_double,none,2,l(triangle,1))]).
train(east,[c(1,rectangle,long,not_double,flat,3,l(utriangle,1)),c(2,hexagon,
	short,not_double,flat,2,l(triangle,1)),c(3,rectangle,
	short,not_double,none,2,l(circle,1))]).
train(east,[c(1,rectangle,short,not_double,none,2,l(rectangle,1)),c(2,ellipse,
	short,not_double,arc,2,l(diamond,1)),c(3,rectangle,short,
	double,none,2,l(triangle,1)),c(4,bucket,short,not_double,
	none,2,l(triangle,1))]).
train(east,[c(1,rectangle,short,not_double,flat,2,l(circle,1)),c(2,rectangle,
	long,not_double,flat,3,l(rectangle,1)),c(3,rectangle,
	short,double,none,2,l(triangle,1))]).
train(east,[c(1,rectangle,long,not_double,jagged,3,l(rectangle,1)),c(2,hexagon,
	short,not_double,flat,2,l(circle,1)),c(3,rectangle,short,
	not_double,none,2,l(triangle,1)),c(4,rectangle,long,not_double,
	jagged,2,l(rectangle,0))]).
train(east,[c(1,rectangle,long,not_double,none,2,l(hexagon,1)),c(2,rectangle,
	short,not_double,none,2,l(rectangle,1)),c(3,rectangle,
	short,not_double,flat,2,l(triangle,1))]).
train(east,[c(1,rectangle,short,not_double,peaked,2,l(rectangle,1)),c(2,
	bucket,short,not_double,none,2,l(rectangle,1)),c(3,rectangle,
	long,not_double,flat,2,l(circle,1)),c(4,rectangle,short,
	not_double,none,2,l(rectangle,1))]).
train(east,[c(1,rectangle,long,not_double,none,2,l(rectangle,3)),c(2,rectangle,
	short,not_double,none,2,l(circle,1)),c(3,rectangle,long,
	not_double,jagged,3,l(hexagon,1)),c(4,u_shaped,short,
	not_double,none,2,l(triangle,1))]).
train(east,[c(1,bucket,short,not_double,none,2,l(triangle,1)),c(2,u_shaped,
	short,not_double,none,2,l(circle,1)),c(3,rectangle,short,
	not_double,none,2,l(triangle,1)),c(4,rectangle,short,
	not_double,none,2,l(triangle,1))]).
train(west,[c(1,rectangle,short,not_double,none,2,l(triangle,1)),
	c(2,rectangle, long,not_double,flat,2,l(circle,3))]).
train(west,[c(1,rectangle,long,not_double,jagged,2,l(circle,0)),c(2,u_shaped,
	short,not_double,none,2,l(triangle,1)),c(3,rectangle,short,
	double,none,2,l(circle,1))]).
train(west,[c(1,u_shaped,short,not_double,none,2,l(circle,1)),c(2,rectangle,
	long,not_double,flat,3,l(rectangle,1))]).
train(west,[c(1,bucket,short,not_double,none,2,l(circle,1)),c(2,rectangle,
	short,not_double,none,2,l(rectangle,1)),c(3,rectangle,
	long,not_double,jagged,3,l(rectangle,1)),c(4,bucket,short,
	not_double,none,2,l(circle,1))]).
train(west,[c(1,rectangle,long,not_double,none,2,l(rectangle,2)),c(2,u_shaped,
	short,not_double,none,2,l(rectangle,1))]).
train(west,[c(1,bucket,short,not_double,none,2,l(rectangle,1)),c(2,rectangle,
	long,not_double,flat,2,l(utriangle,3))]).
train(west,[c(1,rectangle,long,not_double,none,2,l(hexagon,1)),c(2,rectangle,
	short,not_double,none,2,l(circle,1)),c(3,rectangle,short,
	double,none,2,l(circle,1)),c(4,rectangle,long,not_double,
	none,2,l(rectangle,3))]).
train(west,[c(1,u_shaped,short,not_double,none,2,l(triangle,1)),c(2,rectangle,
	long,not_double,none,3,l(rectangle,3))]).
train(west,[c(1,rectangle,long,not_double,flat,3,l(rectangle,3)),
	c(2,rectangle, long,not_double,flat,2,l(rectangle,3)),c(3,rectangle,
	long,not_double,none,2,l(rectangle,0)),c(4,u_shaped,short,
	not_double,none,2,l(triangle,1))]).
train(west,[c(1,rectangle,long,not_double,flat,3,l(hexagon,1)),c(2,u_shaped,
	short,not_double,none,2,l(triangle,1))]).
