# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import workflows.thumbs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True)),
                ('variable', models.CharField(help_text=b'The variable attribute of both the input and the output are important because this is how the data will be accessed in the python function that is executed when the widget runs.', max_length=50)),
                ('required', models.BooleanField()),
                ('parameter', models.BooleanField()),
                ('multi', models.BooleanField(default=False, help_text=b'Inputs with this flag set will behave like this: whenever a connection is added to this input another input will be created on the fly that accepts the same data. In the action function, this will be represented as a list.')),
                ('default', models.TextField(blank=True)),
                ('parameter_type', models.CharField(blank=True, choices=[(b'text', b'Single line'), (b'password', b'Password'), (b'textarea', b'Multi line text'), (b'select', b'Select box'), (b'checkbox', b'Checkbox'), (b'file', b'File')], max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('uid', models.CharField(blank=True, default=b'', max_length=250)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AbstractOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
                ('uid', models.CharField(blank=True, default=b'', max_length=250)),
                ('abstract_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='workflows.AbstractInput')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AbstractOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True)),
                ('variable', models.CharField(help_text=b'The variable attribute of both the input and the output are important because this is how the data will be accessed in the python function that is executed when the widget runs.', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('uid', models.CharField(blank=True, default=b'', max_length=250)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AbstractWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name is the name that will be displayed in the widget repository and under the actual widget itself.', max_length=200)),
                ('action', models.CharField(help_text=b'Action is the name of a python function that will be called when the widget is executed.', max_length=200)),
                ('wsdl', models.URLField(blank=True, help_text=b'WSDL and WSDL method are used if the widget is a call of a Web Service. Web Service widgets are usually not entered in the admin panel, but in the application itself by importing a Web Service.')),
                ('wsdl_method', models.CharField(blank=True, default=b'', max_length=200)),
                ('description', models.TextField(blank=True, help_text=b'Description is used for a human readable description of what a widget does. A user will see this when he right clicks the widget and clicks help.')),
                ('visualization_view', models.CharField(blank=True, default=b'', help_text=b'Visualization view is (like the action) a python function that is a view that will render a template.', max_length=200)),
                ('streaming_visualization_view', models.CharField(blank=True, default=b'', help_text=b'Visualization view is (like the action) a python function that is a view that will render a template.', max_length=200)),
                ('interactive', models.BooleanField(default=False, help_text=b'The widget can be interactive. This means that when a user executes the widget, the action will perform, then the interaction view will be executed and finally the Post interact action will be executed.')),
                ('interaction_view', models.CharField(blank=True, default=b'', max_length=200)),
                ('post_interact_action', models.CharField(blank=True, default=b'', max_length=200)),
                ('image', workflows.thumbs.ThumbnailField(blank=True, help_text=b'Image and Treeview image are deprecated and will be phased out soon. Please use the static image field.', null=True, upload_to=b'images')),
                ('treeview_image', workflows.thumbs.ThumbnailField(blank=True, null=True, upload_to=b'treeview')),
                ('static_image', models.CharField(blank=True, default=b'', help_text=b'In the static image field just enter the filename of the image (without the path). The path will be $package_name$/icons/widget/$filename$ and $package_name$/icons/treeview/$filename$ where the treeview image is the small image that appears in the treeview on the left side and the widget image is the actual normal sized icon for the widget. IMPORTANT: the static image field only works if the package is set.', max_length=250)),
                ('has_progress_bar', models.BooleanField(default=False, help_text=b'The flag has progress bar determines if the widget implements a progress bar.')),
                ('is_streaming', models.BooleanField(default=False, help_text=b'The is streaming flag is currently under construction, please do not use it yet.')),
                ('order', models.PositiveIntegerField(default=1, help_text=b'The Order determines the order in which the widget will be displayed in the repository. This is set automatically when sorting widgets in a single category from the admin.')),
                ('uid', models.CharField(blank=True, default=b'', help_text=b'UID is set automatically when you export a package with the -u switch.', max_length=250)),
                ('package', models.CharField(blank=True, default=b'', help_text=b'Package is the package name. You are encouraged to use packages.', max_length=150)),
                ('windows_queue', models.BooleanField(default=False, help_text=b"This is used for Matjaz Jursic's widgets.")),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('uid', models.CharField(blank=True, default=b'', max_length=250)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflows.Category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'name'),
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('variable', models.CharField(max_length=50)),
                ('required', models.BooleanField()),
                ('parameter', models.BooleanField()),
                ('value', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('multi_id', models.IntegerField(default=0)),
                ('parameter_type', models.CharField(blank=True, choices=[(b'text', b'Single line'), (b'textarea', b'Multi line text'), (b'select', b'Select box'), (b'file', b'File field'), (b'checkbox', b'Checkbox')], max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='workflows.Input')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
                ('variable', models.CharField(max_length=50)),
                ('value', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('inner_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outer_output_rel', to='workflows.Input')),
                ('outer_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_output_rel', to='workflows.Input')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('interaction_waiting', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'regular', b'Regular widget'), (b'subprocess', b'Subprocess widget'), (b'input', b'Input widget'), (b'output', b'Output widget'), (b'for_input', b'For input'), (b'for_output', b'For output'), (b'cv_input', b'Cross Validation input'), (b'cv_output', b'Cross Validation output'), (b'cv_input2', b'Cross Validation input 2'), (b'cv_input3', b'Cross Validation input 3')], default=b'regular', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('abstract_widget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.AbstractWidget')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Untitled workflow', max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default=b'')),
                ('template_parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.Workflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
                ('widget', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_link', to='workflows.Widget')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='widget',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflows.Workflow'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workflows.Workflow'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='output',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='workflows.Widget'),
        ),
        migrations.AddField(
            model_name='input',
            name='inner_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outer_input_rel', to='workflows.Output'),
        ),
        migrations.AddField(
            model_name='input',
            name='outer_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_input_rel', to='workflows.Output'),
        ),
        migrations.AddField(
            model_name='input',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='workflows.Widget'),
        ),
        migrations.AddField(
            model_name='connection',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflows.Input'),
        ),
        migrations.AddField(
            model_name='connection',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflows.Output'),
        ),
        migrations.AddField(
            model_name='connection',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflows.Workflow'),
        ),
        migrations.AddField(
            model_name='category',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='workflows.Workflow'),
        ),
        migrations.AddField(
            model_name='abstractwidget',
            name='category',
            field=models.ForeignKey(help_text=b'Category determines to which category this widget belongs. Categories can be nested.', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflows.Category'),
        ),
        migrations.AddField(
            model_name='abstractwidget',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'If the User field is blank, everyone will see the widget, otherwise just this user. This is mainly used for Web Service imports as they are only visible to users that imported them.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractoutput',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='workflows.AbstractWidget'),
        ),
        migrations.AddField(
            model_name='abstractinput',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='workflows.AbstractWidget'),
        ),
    ]
