# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_executed', models.DateTimeField(auto_now_add=True)),
                ('period', models.IntegerField(default=60)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='workflows.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='StreamWidgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_data', to='streams.Stream')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_data', to='workflows.Widget')),
            ],
        ),
    ]
